### AuthLoginByPassword
POST {{url}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

> {% client.global.set("token", response.body.token) %}

