### AuthLoginByPassword
POST {{url}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

> {% client.global.set("token", response.body.token) %}



### AuthLoginByPassword
POST {{url}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "alena",
  "password": "11112223"
}

> {% client.global.set("token", response.body.token) %}

### AuthLoginByPassword
POST {{url}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "alex",
  "password": "11112222"
}

> {% client.global.set("token", response.body.token) %}

### GetAllUsers
GET {{url}}/users
Accept: Application/json
Content-Type: Application/json
Authorization: Bearer {{token}}


### GetUser
GET {{url}}/users/2
Accept: Application/json
Content-Type: Application/json
Authorization: Bearer {{token}}


### CreateUser
POST {{url}}/auth/new
Accept: Application/json
Content-Type: Application/json


{
  "username": "alex",
  "password": "11112222",
  "email": "test2@gmail.com"
}



### UpdateUser
PATCH {{url}}/users/1
Accept: Application/json
Content-Type: Application/json
Authorization: Bearer {{token}}

{


  "password": "12345678"


}


### DeleteUser
DELETE {{url}}/users/1
Accept: Application/json
Content-Type: Application/json
Authorization: Bearer {{token}}

