### Tasks List
GET {{url}}/tasks
Accept: Application/json
Content-Type: Application/json
Authorization: Bearer {{token}}


### Create Task
POST {{url}}/tasks/new
Accept: Application/json
Content-Type: Application/json
Authorization: Bearer {{token}}

{
  "title": "Note",
  "description": "bla bla bla",
  "deadline": {
    "deadline_at": "2026-01-22T16:57:00Z"
  }
}

> {%
    client.global.set("id", response.body.id);
%}

### Create Task
POST {{url}}/tasks/new
Accept: Application/json
Content-Type: Application/json
Authorization: Bearer {{token}}

{
  "title": "Note2",
  "description": "la la land"
}

> {%
    client.global.set("id", response.body.id);
%}


### Get Task
GET {{url}}/tasks/23
Accept: Application/json
Content-Type: Application/json
Authorization: Bearer {{token}}

### Update Task
PATCH {{url}}/tasks/4
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "cart",
  "description": "1 + 1"
}

### Delete Task
DELETE {{url}}/tasks/2
Accept: Application/json
Content-Type: Application/json
Authorization: Bearer {{token}}


### Status Task
POST {{url}}/tasks/1/toggle-status
Accept: Application/json
Content-Type: Application/json
Authorization: Bearer {{token}}


